# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Junu Kim
title: Ph.D Student
email: kjune0322@kaist.ac.kr
website: starmpcc.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: junukim01
github_username:  starmpcc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Junu Kim, a Ph.D student in KAIST Graduate School of AI. I'm interested in machine learning for healthcare (ML4H).


content:
  - title: Lecture
    layout: list
    content:
      - layout: top-middle
        title: "KoSAIM 2023 Summer School Hands-on Session: Transformer"
        link: https://github.com/starmpcc/KoSAIM2023-Transformer
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "CAMEL: Clinically Adapted Model Enhanced from LLaMA"
        description: |
          Sunjun Kweon\*, __Junu Kim__\*, Seongsu Bae\*\*, Eunbyeol Cho\*\*, Sujeong Im\*\*, Jiyoun Kim\*\*, Gyubok Lee\*\*, JongHak Moon\*\*, JeongWoo Oh\*\*, Edward Choi

          \* equal contribution

          \*\* alphabetical order

        link: https://starmpcc.github.io/CAMEL/
        # link_text: Project Website
        additional_links:
          - title:  CAMEL
            icon: fab fa-github
            url: https://github.com/starmpcc/CAMEL
          - title:  CAMEL Demo
            url: https://starmpcc-camel-demo-demo-i7ajms.streamlit.app/
            icon: fab fa-labtop
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           Clinically Adapted LLaMA, pre-trained and fine-tuned on clinical notes.
  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Universal EHR Federated Learning Framework
        description: |
          __Junu Kim__, Kyunghoon Hur, Seongjun Yang, Edward Choi

          This paper is published on ML4H 2022 Extended Abstract Track.
        link: https://arxiv.org/abs/2211.07300
        # link_text: Project Website
        additional_links:
          - title:  UniFL
            icon: fab fa-github
            url: https://github.com/starmpcc/UniFL
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           Our study is the first approach to unify heterogeneous EHRs into a single FL framework.
          

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KAIST Graduate School for AI
        caption: 2022-
        sub_title: Ms-PhD Integrated Course
        description: |
          I'm currently being supervised by Professor [Edward Choi](https://mp2893.com/)

          My current interest is Machine Learning for Healthcare (ML4H) and long sequence modeling.

      - layout: left
        title: KAIST
        caption: 2018 - 2022
        sub_title: BSc Computer Science
        Description:
          I graduated KAIST School of Computing at 2022.02.
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
